server:
  port: ${SERVER_PORT:4004}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: ${AUTH_SERVICE_URL:http://localhost:4005}
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: patient-service-route
          uri: ${PATIENT_SERVICE_URL:http://localhost:4000}
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation
        - id: patient-docs-route
          uri: ${PATIENT_SERVICE_URL:http://localhost:4000}
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs
        - id: auth-docs-route
          uri: ${AUTH_SERVICE_URL:http://localhost:4005}
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
